### ISSUE TITLE
分红送的股票份额无法卖出

### ISSUE THREAD

**Issue by weepo-bean** [zillionare/trader-client#10]
分红送的股票份额无法卖出，跟送股的日期也没有关系，过了一段时间还是无法卖出。如下：

我在2020年6月10日账户中有15600股：
![图片](https://user-images.githubusercontent.com/57930570/180159480-74ce5a4b-d413-4d91-9fee-62f566ba15b3.png)

当日下单买入补仓500股到16100股，并且下单成功：
![图片](https://user-images.githubusercontent.com/57930570/180159604-04056b8a-80b8-4099-b12c-e808b6bce85b.png)

在6月17日查询账户中该股分红154股，总股数为16254股：
![图片](https://user-images.githubusercontent.com/57930570/180159838-c3097761-ac0f-4194-a95b-e62785b9839b.png)

然后在6月17日清仓该股票的时候，下单卖出全部16254股，返回的成交信息中，只卖出非分红送股的16100股：
![图片](https://user-images.githubusercontent.com/57930570/180160108-2eab5a91-3c8e-4275-9879-f914e90b0799.png)

在成交完之后查询该股票仓位，账户中显示该股票仓位为（分红送股的股票份额无法卖出）：
![图片](https://user-images.githubusercontent.com/57930570/180160599-6e0cff78-a615-4048-9521-252b2ba18cd6.png)

**Comment by zillionare** [comment]
这是一个backtesting的issue,已重新创建在https://github.com/zillionare/backtesting/issues/13。
