### ISSUE TITLE
股票买入后几个交易日，client.postion()中，的sellable 一直显示为0，使用client.sell_percent()不能全部成功卖出股票

### ISSUE THREAD

**Issue by Johnny-168** [zillionare/trader-client#11]
* zillionare-trader-client version:  zillionare-trader-client 0.3.10
* Python version: Python 3.8
* Operating System: Win 10

### Description
client.buy()  返回结果：
{'tid': '6dc91bb4-2652-48c5-a38f-2036b92f2413', 'eid': 'b6d4bd8d-7db8-4f70-addf-1f2acd2123b4', 'security': '002931.XSHE', 'order_side': '买入', 'price': 14.488335877862596, 'filled': 65500, 'time': datetime.datetime(2022, 1, 18, 9, 35), 'trade_fees': 94.9}

回测中，2022-01-18买入002931.XSHE后，在随后几个交易日19日，20日，client.position() 返回结果中，最后一个元素的sellable  的值是0， 

模拟第255天: 2022-01-19 00:00:00 ==================================================
position
 [('600188.XSHG', 34411.76265478, 34411.76265478,  9.63333391)
 ('002739.XSHE',  7400.        ,  7400.        , 19.69      )
 ('601117.XSHG',  4761.0397    ,  4761.0397    ,  6.51032655)
 ('002931.XSHE', 65500.        ,     0.        , 14.48833588)]

模拟第256天: 2022-01-20 00:00:00 ==================================================
position
 [('600188.XSHG', 34411.76265478, 34411.76265478,  9.63333391)
 ('002739.XSHE',  7400.        ,  7400.        , 19.69      )
 ('601117.XSHG',  4761.0397    ,  4761.0397    ,  6.51032655)
 ('002931.XSHE', 65500.        ,     0.        , 14.48833588)]

在2022-01-20 此股票发出卖出交易，使用client.sell_percent() 全部卖出，显示卖出成功： 但是只是卖出部分，即20800股，如下返回值
[{'tid': '03774906-ae7b-4dde-9fba-071acbcdf66b', 'eid': 'b6d4bd8d-7db8-4f70-addf-1f2acd2123b4', 'security': '002931.XSHE', 'order_side': '卖出', 'price': 14.5, 'filled': 20800.0, 'time': '2022-01-20T09:30:05', 'trade_fees': 30.16}]

当日卖出后，及21日查询持仓：

模拟第257天: 2022-01-21 00:00:00 ==================================================
position
 [('600188.XSHG', 34411.76265478, 34411.76265478,  9.63333391)
 ('002739.XSHE',  7400.        ,  7400.        , 19.69      )
 ('601117.XSHG',  4761.0397    ,  4761.0397    ,  6.51032655)
 ('002931.XSHE', 44700.        , 44700.        , 14.48833588)]

002931.XSHE，仍然显示有持仓；20日的卖出没有全部成交， 仍有44700股没有卖出。

**Comment by zillionare** [comment]
如果要查询指定日期的持仓，需要传入查询日期。
仅成交部分的原因是因为，当天开盘价即最高价，此后没有收盘价高于开盘价，因此无法卖出。
