### ISSUE TITLE
仓位中有只长期停牌股票时交易异常

### ISSUE THREAD

**Issue by weepo-bean** [zillionare/trader-client#13]
2020年7月3日，仓位中有停牌股票‘601558.XSHG’，当日尝试卖出其他股票正常。在7月17日下一次调仓时尝试交易其他股票时报错。7月17日仓位为：
![图片](https://user-images.githubusercontent.com/57930570/182052382-8b1b19f3-faf1-4fd4-a79f-ad19d11b8fcd.png)

下单代码为：
r = client.market_sell(security=‘300021.XSHE’, volume=35900.0, order_time=arrow.get('2020-07-17 09:31').naive)

报错信息为：
![图片](https://user-images.githubusercontent.com/57930570/182052473-2b4167bb-eb89-477c-9925-66adb5f2b14b.png)

**Comment by zillionare** [comment]
move to https://github.com/zillionare/backtesting/issues/15
