### ISSUE TITLE
仓位中有停牌股票时下单显示矢量化错误

### ISSUE THREAD

**Issue by weepo-bean** [zillionare/trader-client#14]
2020年7月3日，仓位中有停牌股票‘601558.XSHG’，当日尝试卖出其他股票正常。在7月17日下一次调仓时尝试交易其他股票时报错。7月17日仓位为：
![图片](https://user-images.githubusercontent.com/57930570/182080998-034e09c8-1852-4533-87b1-d2b03d7a9f07.png)

下单代码为：
r = client.market_sell(security=‘300021.XSHE’, volume=35900.0, order_time=arrow.get('2020-07-17 09:31').naive)

报错信息为：
市价卖出 failed: 499, cannot call `vectorize` on size 0 inputs unless `otypes` is set

**Comment by zillionare** [comment]
moved to zillionare/backtesting#16 and close this
