### ISSUE TITLE
invalid type promotion with structured datatype(s)

### ISSUE THREAD

**Issue by weepo-bean** [zillionare/trader-client#18]
在‘2020-05-11’日查询仓位信息为：
![图片](https://user-images.githubusercontent.com/57930570/186801464-217978fa-2e11-473d-b257-fef768705bf3.png)

经查询，000620.XSHE当日未停牌，下单时间点9点31分未跌停，在9点31日发出下单指令：
client.market_sell(security='000620.XSHE', volume=100, order_time=arrow.get('2020-05-11 09:31').naive)

报错：
TradeError: invalid type promotion with structured datatype(s).: (499, 'invalid type promotion with structured datatype(s).')

**Comment by zillionare** [comment]
duplicated with https://github.com/zillionare/backtesting/issues/26

please submit issues under repo 'backtesting' if you found (499, blah blah) in error message.
